const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    // //admin
    FETCH_GENDER: 'FETCH_GENDER',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIL: 'FETCH_GENDER_FAIL',

    // admin create user
    FETCH_CREATE_USER: 'FETCH_CREATE_USER',
    FETCH_CREATE_USER_SUCCESS: 'FETCH_CREATE_USER_SUCCESS',
    FETCH_CREATE_USER_FAIL: 'FETCH_CREATE_USER_FAIL',

    // admin get all user
    FETCH_GET_ALL_USER: 'FETCH_GET_ALL_USER',
    FETCH_GET_ALL_USER_SUCCESS: 'FETCH_GET_ALL_USER_SUCCESS',
    FETCH_GET_ALL_USER_FAIL: 'FETCH_GET_ALL_USER_FAIL',

    // admin delete user

    DETELE_USER: 'DETELE_USER',
    DETELE_USER_SUCCESS: 'DETELE_USER_SUCCESS',
    DETELE_USER_FAIL: 'DETELE_USER_FAIL',

    // update user

    UPDATE_USER: 'UPDATE_USER',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',
    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
});

export default actionTypes;
